---
sidebar: false
toc: false
---

# Workshop Schedule

## Pre-reading
* [Introduction to scRNA-seq](https://hbctraining.github.io/Intro-to-scRNAseq-Quarto/lessons/01_intro_to_scRNA-seq.html)
* [scRNA-seq: From sequence reads to count matrix](https://hbctraining.github.io/Intro-to-scRNAseq-Quarto/lessons/02_SC_generation_of_count_matrix.html)
* [scRNA-seq: From counts to clusters](01_counts_to_clusters_overview.qmd)
* [Download this project](https://www.dropbox.com/scl/fi/c3ggrdttuk3cqovqocy1a/Pseudobulk_workshop.zip?rlkey=nehku3i8mrtkbibe4wvt04n40&st=t8noj7w8&dl=1)

## Day 1

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:15 | [Workshop introduction](../slides/workshop_intro_slides.pdf) |  Will |
| 10:15 - 10:45 | Pre-reading review and Q&A | All |
| 10:45 - 10:50 | Break | |
| 10:50 - 11:25 | [Project setup and data exploration](02_setup_intro_dataset.qmd) | Will |
| 11:25 - 11:55 | [Differential expression analysis using `FindMarkers()`](03_DEanalysis_using_FindMarkers.qmd) | Noor |
| 11:55 - 12:00 | Overview of self-learning materials and homework submission | Will |

### Before the next class:

I. Please **study the contents** and **work through all the code** within the following lessons:
 
   1. [Differential expression analysis visualization from `FindMarkers()`](04_DEanalysis_FindMarkers_visualization.qmd)
      <details>
       <summary><i>Click here for a preview of this lesson</i></summary>
       <br> Visualization of the differential expression data from <code>FindMarkers()</code> can give important insights into our biological question of interest.<br><br>In this lesson you will:<br>
             - Create visualizations for differentially expressed genes<br>
             - Discuss other statistical tests for differential expression analysis<br>
<br>
        </details>

  2. [Theory of PCA](05_theory_of_PCA.qmd)
      <details>
       <summary><i>Click here for a preview of this lesson</i></summary>
       <br> Before we can begin the next steps of the workflow, we need to make sure you have a good understanding of Principal Components Analysis (PCA). This method will be utilized in the scRNA-seq analysis workflow, and this foundation will help you better navigate those steps and interpretation of results. <br><br>In this lesson you will:<br>
           - Derive the covariance matrix used for Principal Components Analysis<br>   
           - Explain the roles of eigenvectors and eigenvalues within a Principal Components Analysis<br>
           - Compare and contrast our Principal Components Analysis to the output of <code>prcomp()</code><br><br>
        </details>       
         

II. **Submit your work**:
   * Each lesson above contains exercises; please go through each of them.
   * **Submit your answers** to the exercises using [this Google form](https://forms.gle/sZeXdaUwf4uwwMah7) on **the day *before* the next class**.
   


### Questions?
* ***If you get stuck due to an error*** while running code in the lesson, [email us](mailto:hbctraining@hsph.harvard.edu) 

***

## Day 2

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:30 | Self-learning lessons discussion | All |
| 10:30 - 11:15 | [Aggregating counts by celltype using pseudobulk approach](06_pseudobulk_DESeq2.qmd) |  Noor |
| 11:15 - 11:20 | Break | |
| 11:20 - 12:00 | [DE analysis of pseudobulk data using DESeq2](07_pseudobulk_DE_analysis.qmd) | Will |

### Before the next class:

There is no self-learning for Day 2.

### Questions?
* ***If you have any questions from today***, [email us](mailto:hbctraining@hsph.harvard.edu) 

## Day 3

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:15 | Self-learning lessons discussion | All |
| 10:15 - 10:55 | [Visualization of differentially expressed genes](08_pseudobulk_DE_visualizations.qmd) | Will |
| 10:55 - 11:00|  Break |  |
| 11:00 - 11:55 | [Comparison of results from different DE approaches](09_DE_comparisons.qmd) | Noor |
| 11:55 - 12:00 | Overview of self-learning materials and homework submission | Will |

### Before the next class:

I. Please **study the contents** and **work through all the code** within the following lessons:
   1. [Functional Analysis](10_functional_analysis_pseudobulk.qmd)
      <details>
       <summary><i>Click here for a preview of this lesson</i></summary>
         <br>Now that we have significant genes, let's gain some biological insight <br><br>In this lesson, we will:<br>
             - Discuss approaches for functional analysis<br>
             - Use clusterProfiler to run over-representation analsyis and visualize results<br>
             - Use clusterProfiler to run GSEA <br><br>
        </details>

II. **Submit your work**:
   * Each lesson above contains exercises; please go through each of them.
   * **Submit your answers** to the exercises using [this Google form](https://forms.gle/7bmFiRZc6MQX7YXm7) on **the day *before* the next class**.

### Questions?
* ***If you get stuck due to an error*** while running code in the lesson, [email us](mailto:hbctraining@hsph.harvard.edu) 


***


## Day 4

| Time |  Topic  | Instructor |
|:-----------:|:----------:|:--------:|
| 10:00 - 10:30 | Self-learning lessons discussion | All |
| 10:30 - 11:30| [Methods for Differental Abundance](11_differential_abundance.qmd)  | Noor  |
| 11:30 - 11:35 | Break |
| 11:35 - 11:45| Discussion and Q&A | All |
| 11:45 - 12:00| [Wrap-up](../lectures/Workshop_wrapup.pdf) | Will |

***

## Resources
